-- Functional schema alignment for all active modules in the frontend.
-- This migration is idempotent and focuses on avoiding runtime errors caused by
-- missing tables/columns or incompatible relations.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- terceros
CREATE TABLE IF NOT EXISTS public.terceros (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    rut TEXT UNIQUE NOT NULL,
    razon_social TEXT NOT NULL,
    direccion TEXT,
    telefono TEXT,
    email TEXT,
    tipo TEXT NOT NULL DEFAULT 'cliente',
    estado TEXT DEFAULT 'activo',
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE public.terceros ADD COLUMN IF NOT EXISTS plazo_pago_dias INTEGER DEFAULT 30;
ALTER TABLE public.terceros ADD COLUMN IF NOT EXISTS es_trabajador BOOLEAN DEFAULT false;
ALTER TABLE public.terceros ADD COLUMN IF NOT EXISTS cargo TEXT;

-- facturas
CREATE TABLE IF NOT EXISTS public.facturas (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ DEFAULT now(),
    tipo TEXT NOT NULL DEFAULT 'venta',
    monto NUMERIC(12,2) NOT NULL DEFAULT 0,
    fecha_emision DATE DEFAULT CURRENT_DATE,
    fecha_vencimiento DATE,
    numero_documento TEXT,
    descripcion TEXT,
    estado TEXT DEFAULT 'pendiente',
    tercero_id UUID REFERENCES public.terceros(id) ON DELETE SET NULL,
    archivo_url TEXT,
    tercero_nombre TEXT,
    rut TEXT
);

ALTER TABLE public.facturas ADD COLUMN IF NOT EXISTS fecha_vencimiento DATE;
ALTER TABLE public.facturas ADD COLUMN IF NOT EXISTS numero_documento TEXT;
ALTER TABLE public.facturas ADD COLUMN IF NOT EXISTS tercero_nombre TEXT;
ALTER TABLE public.facturas ADD COLUMN IF NOT EXISTS rut TEXT;
ALTER TABLE public.facturas ADD COLUMN IF NOT EXISTS archivo_url TEXT;
ALTER TABLE public.facturas ADD COLUMN IF NOT EXISTS descripcion TEXT;
ALTER TABLE public.facturas ADD COLUMN IF NOT EXISTS tercero_id UUID;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'facturas_tercero_id_fkey'
          AND conrelid = 'public.facturas'::regclass
    ) THEN
        ALTER TABLE public.facturas
        ADD CONSTRAINT facturas_tercero_id_fkey
        FOREIGN KEY (tercero_id) REFERENCES public.terceros(id) ON DELETE SET NULL;
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_facturas_tercero_id ON public.facturas(tercero_id);
CREATE INDEX IF NOT EXISTS idx_facturas_tipo_estado ON public.facturas(tipo, estado);
CREATE INDEX IF NOT EXISTS idx_facturas_fecha_vencimiento ON public.facturas(fecha_vencimiento);

-- movimientos_banco
CREATE TABLE IF NOT EXISTS public.movimientos_banco (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ DEFAULT now(),
    fecha_movimiento DATE NOT NULL,
    descripcion TEXT,
    monto NUMERIC(12,2) NOT NULL,
    tipo TEXT,
    estado TEXT DEFAULT 'no_conciliado',
    numero_documento TEXT,
    saldo NUMERIC(12,2),
    id_secuencial BIGINT GENERATED BY DEFAULT AS IDENTITY,
    n_operacion TEXT,
    sucursal TEXT
);

ALTER TABLE public.movimientos_banco ADD COLUMN IF NOT EXISTS numero_documento TEXT;
ALTER TABLE public.movimientos_banco ADD COLUMN IF NOT EXISTS saldo NUMERIC(12,2);
ALTER TABLE public.movimientos_banco ADD COLUMN IF NOT EXISTS n_operacion TEXT;
ALTER TABLE public.movimientos_banco ADD COLUMN IF NOT EXISTS sucursal TEXT;
ALTER TABLE public.movimientos_banco ADD COLUMN IF NOT EXISTS id_secuencial BIGINT;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'movimientos_banco'
          AND column_name = 'id_secuencial'
    ) THEN
        CREATE SEQUENCE IF NOT EXISTS public.movimientos_banco_id_secuencial_seq;
        ALTER TABLE public.movimientos_banco
            ALTER COLUMN id_secuencial SET DEFAULT nextval('public.movimientos_banco_id_secuencial_seq');
        UPDATE public.movimientos_banco
        SET id_secuencial = nextval('public.movimientos_banco_id_secuencial_seq')
        WHERE id_secuencial IS NULL;
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_movimientos_id_secuencial ON public.movimientos_banco(id_secuencial DESC);
CREATE INDEX IF NOT EXISTS idx_movimientos_n_operacion ON public.movimientos_banco(n_operacion);
CREATE INDEX IF NOT EXISTS idx_movimientos_estado ON public.movimientos_banco(estado);

-- rendiciones
CREATE TABLE IF NOT EXISTS public.rendiciones (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ DEFAULT now(),
    fecha DATE DEFAULT CURRENT_DATE,
    tercero_id UUID REFERENCES public.terceros(id) ON DELETE SET NULL,
    tercero_nombre TEXT,
    monto_total NUMERIC(12,2) NOT NULL DEFAULT 0,
    estado TEXT DEFAULT 'pendiente',
    descripcion TEXT,
    archivos_urls TEXT[] DEFAULT '{}'
);

ALTER TABLE public.rendiciones ADD COLUMN IF NOT EXISTS fecha DATE DEFAULT CURRENT_DATE;
ALTER TABLE public.rendiciones ADD COLUMN IF NOT EXISTS tercero_id UUID;
ALTER TABLE public.rendiciones ADD COLUMN IF NOT EXISTS tercero_nombre TEXT;
ALTER TABLE public.rendiciones ADD COLUMN IF NOT EXISTS monto_total NUMERIC(12,2) NOT NULL DEFAULT 0;
ALTER TABLE public.rendiciones ADD COLUMN IF NOT EXISTS estado TEXT DEFAULT 'pendiente';
ALTER TABLE public.rendiciones ADD COLUMN IF NOT EXISTS descripcion TEXT;
ALTER TABLE public.rendiciones ADD COLUMN IF NOT EXISTS archivos_urls TEXT[] DEFAULT '{}';

CREATE INDEX IF NOT EXISTS idx_rendiciones_tercero_id ON public.rendiciones(tercero_id);

-- rendicion_detalles
CREATE TABLE IF NOT EXISTS public.rendicion_detalles (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    rendicion_id UUID REFERENCES public.rendiciones(id) ON DELETE CASCADE,
    descripcion TEXT NOT NULL,
    monto NUMERIC(12,2) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_rendicion_detalles_rendicion_id ON public.rendicion_detalles(rendicion_id);

-- facturas_pagos
CREATE TABLE IF NOT EXISTS public.facturas_pagos (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    factura_id UUID REFERENCES public.facturas(id) ON DELETE CASCADE,
    rendicion_id UUID REFERENCES public.rendiciones(id) ON DELETE CASCADE,
    movimiento_banco_id UUID REFERENCES public.movimientos_banco(id) ON DELETE CASCADE,
    monto_aplicado NUMERIC(12,2) NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE public.facturas_pagos ADD COLUMN IF NOT EXISTS factura_id UUID;
ALTER TABLE public.facturas_pagos ADD COLUMN IF NOT EXISTS rendicion_id UUID;
ALTER TABLE public.facturas_pagos ADD COLUMN IF NOT EXISTS movimiento_banco_id UUID;
ALTER TABLE public.facturas_pagos ADD COLUMN IF NOT EXISTS monto_aplicado NUMERIC(12,2) NOT NULL DEFAULT 0;
ALTER TABLE public.facturas_pagos ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT now();
ALTER TABLE public.facturas_pagos ALTER COLUMN factura_id DROP NOT NULL;

CREATE INDEX IF NOT EXISTS idx_facturas_pagos_factura ON public.facturas_pagos(factura_id);
CREATE INDEX IF NOT EXISTS idx_facturas_pagos_rendicion ON public.facturas_pagos(rendicion_id);
CREATE INDEX IF NOT EXISTS idx_facturas_pagos_movimiento ON public.facturas_pagos(movimiento_banco_id);

-- budgets and cashflow modules
CREATE TABLE IF NOT EXISTS public.gastos_recurrentes (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ DEFAULT now(),
    descripcion TEXT NOT NULL,
    monto NUMERIC(12,2) NOT NULL,
    dia_pago INTEGER CHECK (dia_pago BETWEEN 1 AND 31),
    categoria TEXT,
    activo BOOLEAN DEFAULT true
);

CREATE TABLE IF NOT EXISTS public.presupuestos (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ DEFAULT now(),
    mes DATE NOT NULL,
    categoria TEXT NOT NULL,
    monto_presupuestado NUMERIC(12,2) NOT NULL,
    UNIQUE(mes, categoria)
);

-- users module
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    email TEXT,
    role TEXT DEFAULT 'user',
    created_at FLOAT DEFAULT EXTRACT(EPOCH FROM now())
);

-- internal automation queue (keep here too for full alignment)
CREATE TABLE IF NOT EXISTS public.collection_reminders (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    tercero_id UUID REFERENCES public.terceros(id) ON DELETE SET NULL,
    nombre TEXT NOT NULL,
    email TEXT NOT NULL,
    saldo_total NUMERIC(12,2) NOT NULL DEFAULT 0,
    antiguedad INTEGER NOT NULL DEFAULT 0,
    status TEXT NOT NULL DEFAULT 'queued',
    error_message TEXT,
    processed_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_collection_reminders_status ON public.collection_reminders(status, created_at);
